"""Professional, self-contained audit report generator."""
from html import escape
from pathlib import Path


def generate_report(data, output_dir: Path):
    findings=data.get('findings',[]); remediations=data.get('remediations',[]); metrics=data.get('metrics',{}); steps=data.get('steps',[]); paths=data.get('paths',[]); evidence=data.get('evidence',[])
    status=data.get('status','FAILED'); outcome=data.get('outcome',status)
    cls={'SUCCESS':'ok','FAILED':'bad','OUT_OF_STOCK':'stock','UNAVAILABLE':'stock','REGRESSION':'bad'}.get(status,'warn')
    def rows(items, fn, empty, cols):
        return ''.join(fn(x) for x in items) or f'<tr><td colspan="{cols}">{empty}</td></tr>'
    finding_rows=rows(findings,lambda f:f'<tr><td><b>{escape(str(f.get("severity","MEDIUM")))}</b></td><td>{escape(str(f.get("kind","UX")))}</td><td>{escape(str(f.get("title","Finding")))}</td><td>{escape(str(f.get("evidence","")))}</td><td>{escape(str(f.get("impact","")))}</td></tr>','No findings detected.',5)
    rem_rows=rows(remediations,lambda r:f'<tr><td><b>{escape(str(r.get("priority","MEDIUM")))}</b></td><td>{escape(str(r.get("finding","")))}</td><td>{escape(str(r.get("recommendation","")))}</td><td>{escape(str(r.get("validation","")))}</td></tr>','No remediation recommendations generated.',4)
    step_rows=rows(steps,lambda s:f'<tr><td>{s.get("step","")}</td><td>{escape(str(s.get("action","")))}</td><td>{escape(str(s.get("target","")))}</td><td class="{"good" if s.get("ok") else "badtxt"}">{"VERIFIED" if s.get("ok") else "FAILED"}</td><td>{escape(str(s.get("url_after","")))}</td><td>{s.get("duration_sec",0)}s</td></tr>','No actions recorded.',6)
    path_rows=''.join(f'<div class="path"><b>Path {i}</b> · {escape(str(p.get("status","explored")).upper())}<br>{escape(" → ".join(p.get("nodes",[])))}</div>' for i,p in enumerate(paths,1)) or '<p>No multi-path data recorded.</p>'
    evidence_html=''.join(f'<figure><img src="{escape(str(e.get("url","")))}" alt="Audit evidence step {e.get("step","")}"><figcaption>Step {e.get("step","")} · {escape(str(e.get("caption","")))}</figcaption></figure>' for e in evidence[:18]) or '<p>No screenshots were captured.</p>'
    regression=data.get('regression') or {}
    regression_html=''
    if regression:
        regression_html=f'''<section><h2>V1 Baseline → V2 Regression</h2><div class="grid"><div class="metric"><small>V1 status</small><b>{escape(str(regression.get("v1_status","—")))}</b></div><div class="metric"><small>V2 status</small><b>{escape(str(regression.get("v2_status","—")))}</b></div><div class="metric"><small>Baseline checkpoints</small><b>{regression.get("baseline_checkpoints",0)}</b></div><div class="metric"><small>Matched checkpoints</small><b>{regression.get("matched_checkpoints",0)}</b></div></div><p class="notice">{escape(str(regression.get("summary","")))}</p><h3>Missing V1 checkpoints</h3><pre>{escape("\n".join(regression.get("missing_checkpoints",[])) or "None")}</pre></section>'''
    metric_names=[('Steps','steps'),('Verified actions','verified_actions'),('Verification rate','verification_rate'),('Pages visited','pages_visited'),('Average step time','avg_step_sec'),('UX friction','friction_score'),('Accessibility findings','accessibility'),('Total findings',None),('Critical / High','critical_high'),('Paths',None),('Errors','errors'),('Repeated states','repeated_actions'),('Backtracks','backtracks'),('Dead ends','dead_ends'),('Recovery actions','recovery_actions'),('Goal checks','goal_checks'),('Exact product evidence','goal_match_evidence'),('Outcome confidence','outcome_confidence')]
    metric_html=''
    for label,key in metric_names:
        val=len(findings) if label=='Total findings' else len(paths) if label=='Paths' else metrics.get(key,0)
        if label=='Verification rate': val=f'{val}%'
        if label=='Average step time': val=f'{val}s'
        if label=='Outcome confidence': val=f'{val}%'
        metric_html+=f'<div class="metric"><small>{escape(label)}</small><b>{escape(str(val))}</b></div>'
    a11y=[f for f in findings if f.get('kind')=='accessibility']
    a11y_rows=rows(a11y,lambda f:f'<tr><td>{escape(str(f.get("severity","MEDIUM")))}</td><td>{escape(str(f.get("title","")))}</td><td>{escape(str(f.get("evidence","")))}</td></tr>','No accessibility-specific findings detected.',3)
    summary=data.get('message','Audit completed.')
    if outcome=='SUCCESS': summary='The auditor satisfied the requested goal using browser-observed evidence and verified the final workflow state.'
    elif outcome=='OUT_OF_STOCK': summary='The requested product constraints matched inventory, but the requested product is out of stock. No substitute was treated as success.'
    elif outcome=='FAILED': summary=data.get('message', 'The requested workflow could not be completed or verified.')
    html=f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Autonomous UI Auditor — {escape(str(data.get("run_id","Report")))}</title><style>
:root{{--bg:#050b14;--panel:#0e192a;--line:#263751;--text:#edf3ff;--muted:#98a9c3;--accent:#7c6cff;--ok:#42d392;--bad:#ff7070;--stock:#ffbc55}}*{{box-sizing:border-box}}body{{margin:0;background:linear-gradient(135deg,#040811,#0a1322 55%,#101a2d);color:var(--text);font:15px Inter,system-ui,sans-serif;line-height:1.55}}main{{max-width:1300px;margin:auto;padding:28px}}header,section{{background:rgba(14,25,42,.96);border:1px solid var(--line);border-radius:20px;padding:24px;margin-bottom:18px;box-shadow:0 20px 60px #0006}}h1{{font-size:38px;margin:5px 0 8px}}h2{{font-size:22px;border-bottom:1px solid var(--line);padding-bottom:10px}}h3{{margin-top:24px}}.eyebrow{{color:#b8b2ff;font-weight:900;letter-spacing:.12em;font-size:12px;text-transform:uppercase}}.status{{display:inline-block;padding:8px 15px;border-radius:999px;font-weight:900}}.ok{{background:var(--ok);color:#00190e}}.bad{{background:var(--bad);color:#2b0000}}.stock{{background:var(--stock);color:#291900}}.warn{{background:#f3cf61;color:#261c00}}.grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}}.metric{{background:#091322;border:1px solid var(--line);border-radius:14px;padding:15px}}.metric small{{display:block;color:var(--muted)}}.metric b{{display:block;font-size:22px;margin-top:4px}}table{{width:100%;border-collapse:collapse}}th,td{{padding:11px;border-bottom:1px solid var(--line);vertical-align:top;text-align:left}}th{{color:#b8c5db}}.good{{color:var(--ok);font-weight:800}}.badtxt{{color:var(--bad);font-weight:800}}.path{{padding:13px;border:1px solid var(--line);border-radius:12px;background:#091322;margin:9px 0;font-family:ui-monospace,monospace}}figure{{display:inline-block;width:31%;vertical-align:top;margin:1% 1% 1% 0}}figure img{{width:100%;border-radius:12px;border:1px solid var(--line)}}figcaption{{font-size:12px;color:var(--muted);margin-top:5px}}.notice{{padding:14px;border-left:4px solid var(--accent);background:#111d31;border-radius:10px}}pre{{white-space:pre-wrap;background:#08111f;border:1px solid var(--line);padding:14px;border-radius:10px;color:#cbd5e1}}@media(max-width:900px){{.grid{{grid-template-columns:repeat(2,1fr)}}figure{{width:48%}}}}@media(max-width:600px){{.grid{{grid-template-columns:1fr}}figure{{width:100%}}}}
</style></head><body><main><header><div class="eyebrow">Autonomous UI Auditor · Black-box Agentic QA</div><h1>Full Audit Report</h1><p>{escape(str(data.get('website',data.get('site','ShopEasy'))))} · V{data.get('version',1)} · Run {escape(str(data.get('run_id','—')))} · {escape(str(data.get('timestamp','—')))}</p><span class="status {cls}">{escape(str(outcome))}</span></header>
<section><h2>Executive Summary</h2><p>{escape(summary)}</p><div class="notice"><b>Goal:</b> {escape(str(data.get('goal','')))}</div></section>
<section><h2>Output Metrics</h2><div class="grid">{metric_html}</div></section>
<section><h2>Outcome Classification</h2><p><b>{escape(str(outcome))}</b></p><p><b>SUCCESS:</b> exact requested product evidence + requested workflow state verified.</p><p><b>OUT_OF_STOCK:</b> exact requested inventory match exists but stock is zero.</p><p><b>FAILED:</b> requested workflow could not be completed/verified. Detailed cause appears below.</p></section>
<section><h2>User Journey & Verified Action Trace</h2><table><thead><tr><th>#</th><th>Action</th><th>Target</th><th>Result</th><th>URL after</th><th>Duration</th></tr></thead><tbody>{step_rows}</tbody></table></section>
<section><h2>Multi-Path Exploration</h2>{path_rows}</section>
<section><h2>UI / UX Challenges</h2><table><thead><tr><th>Severity</th><th>Category</th><th>Finding</th><th>Evidence</th><th>Impact</th></tr></thead><tbody>{finding_rows}</tbody></table></section>
<section><h2>Accessibility Audit</h2><table><thead><tr><th>Severity</th><th>Finding</th><th>Evidence</th></tr></thead><tbody>{a11y_rows}</tbody></table><p>Accessibility checks are based on observable black-box browser state.</p></section>
<section><h2>Developer Remediation — Priority Ordered</h2><table><thead><tr><th>Priority</th><th>Finding</th><th>Recommended change</th><th>Validation</th></tr></thead><tbody>{rem_rows}</tbody></table></section>
{regression_html}<section><h2>Evidence Screenshots</h2>{evidence_html}</section><section><h2>Technical Details</h2><p>Automation: Playwright · Reasoning: Gemini 2.5 Flash when configured · Target: {escape(str(data.get('website',data.get('site','ShopEasy'))))} · V{data.get('version',1)} · Run ID: {escape(str(data.get('run_id','—')))}</p></section><footer style="color:var(--muted);padding:20px 0">Generated by Autonomous UI Auditor. This report describes observed black-box behavior and evidence; it does not modify the target website.</footer></main></body></html>'''
    path=output_dir/'report.html'; path.write_text(html,encoding='utf-8'); return path
